### ISSUE TITLE
Memory leak in parsec/ttg.h

### ISSUE THREAD

**Issue by therault** [TESSEorg/ttg#54]
In parsec/ttg.h:754 we do:

`
          std::get<i>(*tuple) = data_wrapper_t<valueT>(wrap(std::forward<Value>(value)));
`

That translates into the version of the wrapper that does

`
        return new std::remove_reference_t<T>(std::forward<T>(data));
`
at parsec/ttg.h:453

Who's responsibility is it to delete this? When should we do it?

We now collect the data_copy_t created for this wrapped data in `complete_task_and_release`, however we don't have the valueT for the different input data at that time. Should we do it there, and move the `complete_task_and_release` in a template-dependent part of the code? How to decide if this is a version that needs to be deleted or not?

**Comment by evaleev** [comment]
@therault the plan for parsec was always to use data_copy_t as the wrapper so that parsec actually has an owning ref to it. current impl is just a stub, do what you need to do. Presumably parsec backend's `wrap` needs to make the data copy. Parsec is the only one who knows how to manage data_copy ...

**Comment by therault** [comment]
the parsec driver now uses parsec_data_copy_t (see PR #63)
