### ISSUE TITLE
data wrappers in parsec driver

### ISSUE THREAD

**Issue by therault** [TESSEorg/ttg#57]
This issue relates to the parsec-data-copy branch (commit 49a24d6cba9), and has multiple points: some are questions, one is a blocker.

1. As I get it, unwrap takes a wrapped data (so a parsec_data_copy_t in this case), and returns the data itself. To do so, I need to extract the type of the data, so I can cast it. As the type is in the prototype of the wrapper (it is templated with the type), I changed the prototype of unwrap for

``` C++
template <template <typename> typename Ttrait, typename T>
      static auto &unwrap(Ttrait<T> &wrapper) 
```

in order to extract the type `T` which is the one I am interested in. Was there an easier approach? I tried

```C++
template <typename T>
      static auto &unwrap(data_wrapper_t<T> &wrapper) 
```

but that didn't compile.

2. I had to define both versions for unwrap: one with a single `&`, the other with double `&&`, I'm not sure why, as in the `template <template <typename> typename Ttrait, typename T>` approach, I was expecting `Ttrait` to be able to match either `data_wrapper_t<T>` or `data_wrapper<T> &`... But that didn't work. The version with the two definition seems to work (i.e. compile at this time...)

3. This is the blocker: lines 781 to 786: 
```C++
auto parsec_wrapper = wrap(std::forward<Value>(value)); 
```
in some instantiation, `parsec_wrapper` gets defined as a `[op with template]::data_wrapper_t<const int>`, but when we do
```C++
std::get<i>(*tuple) = parsec_wrapper;
```
in the same instantiation, `std::get<i>(*tuple)` expects a `[op with template]::data_wrapper_t<int>`, and the compiler refuses to assign one to the other.

I was expecting `T` in my patter matching above (in `unwrap`) to match the type of the argument at position `<i>` but it doesn't.... Why? To reproduce, it should be enough to get the branch and try to compile test-parsec.

**Comment by evaleev** [comment]
> 1. As I get it, unwrap takes a wrapped data (so a parsec_data_copy_t in this case), and returns the data itself. To do so, I need to extract the type of the data, so I can cast it. As the type is in the prototype of the wrapper (it is templated with the type), I changed the prototype of unwrap for
> 
> ```c++
> template <template <typename> typename Ttrait, typename T>
>       static auto &unwrap(Ttrait<T> &wrapper) 
> ```

I think we should just revamp everything here. Starting with the tuple: there is no longer need for it to contain pointers. In fact, since parsec decides where to execute tasks it must use that info to find the corresponding data copy (or, is the proper way to say it: corresponding instance of data copy?? does `parsec_data_copy_t` represent a linked list of all instances of that data or a node in such list???).

The tuple needs to become a tuple of ids for parsec data copies that allow to find them (this could be `parsec_data_copy_t*` or smth else ... see my above question re: what `parsec_data_copy_t` represents, I don't actually know)

> in order to extract the type `T` which is the one I am interested in. Was there an easier approach? I tried

Yes. All unwrap is supposed to do is to extract pointer from `parsec_data_copy_t` and cast it to the desired type. It is not possible to `unwrap` from `parsec_data_copy_t` (since the latter does not contain the type), but `unwrap` is always called from C++ where the type is known. So instead you should just only need to deal with `unwrap_to` (`unwrap` was convenient since it allowed to autodeduce the result type from the type of its argument ... not possible if we use `parsec_data_copy_t` or smth similar to serve as wrapper).

**Comment by therault** [comment]
data wrappers have been from the code
